export const FETCH_TODOS_REQUEST="FETCH_TODOS_REQUEST";
export const FETCH_TODOS_FAILURE="FETCH_TODOS_FAILURE";
export const FETCH_TODOS_SUCCESS="FETCH_TODOS_SUCCESS";
export const CHANGE_COMPLETED_CONDITION="CHANGE_COMPLETED_CONDITION";
export const ADD_ONE_TODO="ADD_ONE_TODO";
export const REMOVE_ONE_TODO="REMOVE_ONE_TODO";